### ISSUE TITLE
panic! on None value

### ISSUE THREAD

**Issue by mustakimur** [ChinmayDeosthali/Rust-Compiler#23]
Check the output:
```
File Contents

�nt print(int in, st msg){
    if(in < 0){
        strcpy(msg, " The sum is below zero!");
    }
    else if(in < 10)
    {
        strcpy(msg, "The sum is a si digit nic.");
    }
    else{
        strcpy(msg, "The sum is large.");
    }
    return 0;
}
int main()
{
    int a, b, c;
    string msg;
    scanf("%d%d%f", &a, &b, &c);
    return print(a, msg);
   
}



Parse Tree :

- call fn print
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/parse_tree.rs:254:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by mustakimur** [comment]
Another case:
```
int print(int in, st msg){
    if(in < 0){
        strcpy(msg, � The sum is below zero!");
    }
    else if(in < 10)
    {
        strcpy(msg, "The sum is a si digit nic.");
    }
    else{
        strcpy(msg, "The sum is large.");
    }
    return 0;
}
int main()
{
    int a, b, c;
    string msg;
    scanf("%d%d%f", &a, &b, &c);
    return print(a, msg);
   
}



Parse Tree :

function print
- return int
- param int in
- param st msg
-- if in lt 0
--- call fn strcpy
---- arg st msg
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/parse_tree.rs:254:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
